### ISSUE TITLE
Login and register do not work

### ISSUE THREAD

**Issue by ruabmbua** [coduno/api#133]
I tried to login with my catcoder login credentials, but it did not work.

I also tried to create a new account, but I encountered an error, where "undefined" was printed out after clicking the register button.

**Comment by lorenzleutgeb** [comment]
Hi! As the issue is closed now but there are no further comments, I'm not quite sure whether you managed to resolve it. Have you been able to log in successfully?

When it comes to registration, we are aware that it fails, as currently only users imported from the CodingContest Platform (which in turn is the place CatCoder is populated from) are allowed to log in and registration is not yet open for anyone. We should have communicated that or at least removed the reference when logging in, I agree. Sorry!

**Comment by ruabmbua** [comment]
I did not resolve the issue but I closed it, because I thought I placed it in the wrong issue tracker (the api project). I wanted to copy it to the app repository, but I had no time left for doing it. Should I recreate the issue, or is it not necessary?

**Comment by lorenzleutgeb** [comment]
OK, nevermind. I looked up your name in our database, and found your account, so you should be able to log in. To verify your password, I could send you the bcrypt record we have, but that should be fine. Could you try to log in again, with the "Developers Console" (or similar) activated and also note the exact time so I can check logs? Thank you.

**Comment by ruabmbua** [comment]
I just logged myself successful in and it worked. I wonder what might have triggered the error before.
